export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAIL = "FOLLOW_USER_FAIL";

export const GET_FOLLOW_DATA_REQUEST = "GET_FOLLOW_DATA_REQUEST";
export const GET_FOLLOW_DATA_SUCCESS = "GET_FOLLOW_DATA_SUCCESS";
export const GET_FOLLOW_DATA_FAIL = "GET_FOLLOW_DATA_FAIL";

export const GET_FOLLOWERS_REQUEST = "GET_FOLLOWERS_REQUEST";
export const GET_FOLLOWERS_SUCCESS = "GET_FOLLOWERS_SUCCESS";
export const GET_FOLLOWERS_FAIL = "GET_FOLLOWERS_FAIL";

export const GET_FOLLOWING_REQUEST = "GET_FOLLOWING_REQUEST";
export const GET_FOLLOWING_SUCCESS = "GET_FOLLOWING_SUCCESS";
export const GET_FOLLOWING_FAIL = "GET_FOLLOWING_FAIL";
