export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAIL = "LIKE_POST_FAIL";

export const GET_ALL_LIKES_REQUEST = "GET_ALL_LIKES_REQUEST";
export const GET_ALL_LIKES_SUCCESS = "GET_ALL_LIKES_SUCCESS";
export const GET_ALL_LIKES_FAIL = "GET_ALL_LIKES_FAIL";


