export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const FIND_SINGLE_POST_REQUEST = "FIND_SINGLE_POST_REQUEST";
export const FIND_SINGLE_POST_SUCCESS = "FIND_SINGLE_POST_SUCCESS";
export const FIND_SINGLE_POST_FAIL = "FIND_SINGLE_POST_FAIL";

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";

export const POST_UPDATE_REQUEST = "POST_UPDATE_REQUEST";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAIL = "POST_UPDATE_FAIL";

export const FIND_POST_BY_USER_REQUEST = "FIND_POST_BY_USER_REQUEST";
export const FIND_POST_BY_USER_SUCCESS = "FIND_POST_BY_USER_SUCCESS";
export const FIND_POST_BY_USER_FAIL = "FIND_POST_BY_USER_FAIL";
